AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/NamedSubject:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 6
